package ar.edu.utn.frc.tup.lciii.Models.Casillas;

public enum TipoCasilla {
    PROVINCIA, FERROCARRIL, BODEGA, COMPANIA_PETROLERA, MARCHE_PRESO, PREMIO_GANADERO,
    CARTA_DESTINO, CARTA_SUERTE, SALIDA, ESTACIONAMIENTO_LIBRE, DESCANSO, COMISARIA, RENTAS, IMPUESTO_VENTAS
}
